# -*- coding: utf-8 -*-
"""Laired Pichardo Islas / Regresión Lineal Incidente critico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DO0K5_u7lUMBuolzbTAPKbWAFEzNZCS1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/dbinemac - Hoja 1.csv', delimiter=("|"))
df

X= df[['ID_ESTADO', 'ID_DISTRITO', 'SECCION']]
y = df['TOTAL_VOTOS_CALCULADOS']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

plt.scatter(X_test['ID_ESTADO'], y_test, color='black')
plt.plot(X_test['ID_ESTADO'], y_pred, color='blue', linewidth=3)  # Línea de regresión
plt.xlabel('ID ESTADO')
plt.ylabel('Total de votos calculados')
plt.title('Regresión Lineal')
plt.show()